SELECT 
    ANOTRN, 
    MESTRN, 
    DIATRN, 
    HORATRN, 
    CANAL, 
    DOCUMENTO,
    TPODOC, 
    NROCTAORG,
    VLRTRAN
FROM ITCLIBRANL.ITCFFACMCN
WHERE ANOTRN = AAAA
AND MESTRN = MM
AND DIATRN = DD
AND DOCUMENTO = nitcliente
AND NROCTAORG = nrocuenta
AND VLRTRAN = valortrn
ORDER BY HORATRN
LIMIT 1
